#!/bin/bash

if [ $# -ne 1 ]; then
   echo "Usage: port"
   exit 1
fi

port=$1
BASE=$HOME/atlas-service
LOG_CFG=$BASE/logging.json

pkill -f traceroute_service
nohup $BASE/CURRENT/traceroute_service.py $port $(cat $BASE/.key) &> $BASE/log < /dev/null &